export const RETRIEVE_MOVIE_LIST = "RETRIEVE_MOVIE_SEARCH";
export const RETRIEVE_MOVIE_SEARCH = "RETRIEVE_TUTORIALS";
export const RETRIEVE_MOVIE_SEARCH_MORE = "RETRIEVE_MOVIE_SEARCH_MORE";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const RETRIEVE_ERROR = "RETRIEVE_ERROR";
